In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
horse = pd.read_csv('/Users/Pawan Kumar/Downloads/horse.csv')

In [2]:
# horse.isna().sum()

In [3]:
horse['rectal_temp'].fillna(38, axis = 0, inplace= True)


In [4]:
horse.pulse.fillna(horse.pulse.mean(), inplace =True)

In [5]:
# horse.isna().sum()
# horse.describe()

In [6]:
horse.respiratory_rate.fillna(30.460581, inplace = True)

In [7]:
horse.nasogastric_reflux_ph.fillna(horse.nasogastric_reflux_ph.mean(), inplace =True)

In [8]:
horse.packed_cell_volume.fillna(46.30740740740741, inplace = True)

In [9]:
horse.total_protein.fillna(24.27443609022557, inplace = True)

In [10]:
horse.abdomo_protein.fillna(3.03960396039604, inplace = True)

In [11]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()

In [12]:
# horse.head()

In [13]:
horse.surgery = pd.get_dummies(horse.surgery, drop_first= True )

In [14]:
# One-hot encoding of all the string columns with categorical values
horse.age = pd.get_dummies(horse.age, drop_first= True )
horse.temp_of_extremities = pd.get_dummies(horse.temp_of_extremities, drop_first= True )
horse.peripheral_pulse = pd.get_dummies(horse.peripheral_pulse, drop_first= True )
horse.mucous_membrane = pd.get_dummies(horse.mucous_membrane, drop_first= True )
horse.capillary_refill_time = pd.get_dummies(horse.capillary_refill_time, drop_first= True )
horse.abdomo_appearance = pd.get_dummies(horse.abdomo_appearance, drop_first= True )
horse.surgical_lesion = pd.get_dummies(horse.surgical_lesion, drop_first= True )
horse.cp_data = pd.get_dummies(horse.cp_data, drop_first= True )
horse.pain = pd.get_dummies(horse.pain, drop_first= True )
horse.peristalsis = pd.get_dummies(horse.peristalsis, drop_first= True )
horse.abdominal_distention = pd.get_dummies(horse.abdominal_distention, drop_first= True)
horse.nasogastric_tube = pd.get_dummies(horse.nasogastric_tube, drop_first= True )
horse.nasogastric_reflux = pd.get_dummies(horse.nasogastric_reflux, drop_first= True )
horse.rectal_exam_feces = pd.get_dummies(horse.rectal_exam_feces, drop_first= True )
horse.abdomen = pd.get_dummies(horse.abdomen, drop_first= True )


In [15]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
horse['outcome'] = horse['outcome'].astype('category')

In [16]:
x = horse.drop('outcome', axis =1)

In [17]:
y = horse['outcome']

In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state = 111, train_size = 0.70)

In [19]:
Model = DecisionTreeClassifier()
Model.fit(x_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [20]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

y_pred = Model.predict(x_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

        died       0.53      0.50      0.51        20
  euthanized       0.33      0.27      0.30        15
       lived       0.69      0.75      0.72        55

    accuracy                           0.61        90
   macro avg       0.52      0.50      0.51        90
weighted avg       0.60      0.61      0.60        90



In [21]:
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred).round(4))

[[10  1  9]
 [ 2  4  9]
 [ 7  7 41]]
0.6111


In [22]:
import warnings
R_model = RandomForestClassifier()
R_model.fit(x_train, y_train)
y_predicted = R_model.predict(x_test)

C:\Users\Pawan Kumar\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [25]:
# from IPython.display import Image
# from sklearn.externals.six import StringIO
# from sklearn.tree import export_graphviz
# import pydotplus, graphviz

C:\Users\Pawan Kumar\Anaconda3\lib\site-packages\sklearn\externals\six.py:31: DeprecationWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", DeprecationWarning)


ModuleNotFoundError: No module named 'pydotplus'

In [24]:
print(accuracy_score(y_test, y_predicted))
print(confusion_matrix(y_test, y_predicted))

0.6666666666666666
[[10  1  9]
 [ 5  0 10]
 [ 5  0 50]]
